CREATE TABLE books(
  id SERIAL PRIMARY KEY,
  isbn VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  year INTEGER NOT NULL);
CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);
CREATE TABLE reviews(
  id SERIAL PRIMARY KEY,
  rating INTEGER NOT NULL,
  content VARCHAR NOT NULL,
  book_id INTEGER REFERENCES books,
  user_id INTEGER REFERENCES users
);
